# File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

from __future__ import annotations

from typing import Optional
from typing_extensions import Literal, Required, Annotated, TypedDict

from ...._types import SequenceNotStr
from ...._utils import PropertyInfo

__all__ = ["GenerateAdvancedParams", "CallToAction"]


class GenerateAdvancedParams(TypedDict, total=False):
    aspect_ratio: Required[Annotated[Literal["16:9", "9:16", "1:1"], PropertyInfo(alias="aspectRatio")]]
    """
    Desired aspect ratio for the video (e.g., 16:9 for landscape, 9:16 for
    portrait).
    """

    length_seconds: Required[Annotated[int, PropertyInfo(alias="lengthSeconds")]]
    """Desired length of the video ad in seconds."""

    prompt: Required[str]
    """
    Textual description for the video ad generation, guiding the AI on content and
    narrative.
    """

    style: Required[Literal["Cinematic", "Documentary", "Animated", "Explainer", "Minimalist", "Vibrant"]]
    """Desired visual style for the video."""

    audience_target: Annotated[
        Optional[Literal["general", "young_adults", "seniors", "entrepreneurs", "corporate"]],
        PropertyInfo(alias="audienceTarget"),
    ]
    """Optional: Target audience for the ad, influencing tone and visuals."""

    background_music: Annotated[
        Optional[Literal["upbeat_corporate", "calming_acoustic", "dramatic_orchestral", "no_music"]],
        PropertyInfo(alias="backgroundMusic"),
    ]
    """Optional: Desired background music theme."""

    brand_assets: Annotated[Optional[SequenceNotStr[str]], PropertyInfo(alias="brandAssets")]
    """Optional: URLs to brand assets (e.g., logos) to be incorporated by AI."""

    brand_colors: Annotated[Optional[SequenceNotStr[str]], PropertyInfo(alias="brandColors")]
    """
    Optional: Array of hex color codes to integrate into the video's branding and
    aesthetic.
    """

    call_to_action: Annotated[Optional[CallToAction], PropertyInfo(alias="callToAction")]
    """Optional: Details for a prominent call-to-action at the end of the video."""

    keywords: Optional[SequenceNotStr[str]]
    """
    Optional: Specific keywords to emphasize in the visual or textual content
    generated by AI.
    """

    subtitles_enabled: Annotated[bool, PropertyInfo(alias="subtitlesEnabled")]
    """
    If true, AI will generate subtitles for the video, primarily for voiceover text.
    """

    voiceover_style: Annotated[
        Optional[Literal["male_professional", "female_friendly", "neutral_authoritative"]],
        PropertyInfo(alias="voiceoverStyle"),
    ]
    """Optional: Desired style/gender for the AI voiceover."""

    voiceover_text: Annotated[Optional[str], PropertyInfo(alias="voiceoverText")]
    """Optional: Text content for an AI-generated voiceover."""


class CallToAction(TypedDict, total=False):
    display_time_seconds: Annotated[int, PropertyInfo(alias="displayTimeSeconds")]
    """Duration in seconds to display the CTA at the end of the video."""

    text: str
    """Text for the Call-to-Action button/overlay."""

    url: str
    """URL for the Call-to-Action."""
