# File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

from __future__ import annotations

from typing import Optional
from typing_extensions import Literal, Required, Annotated, TypedDict

from ...._types import SequenceNotStr
from ...._utils import PropertyInfo

__all__ = ["GenerateStandardParams"]


class GenerateStandardParams(TypedDict, total=False):
    aspect_ratio: Required[Annotated[Literal["16:9", "9:16", "1:1"], PropertyInfo(alias="aspectRatio")]]
    """
    Desired aspect ratio for the video (e.g., 16:9 for landscape, 9:16 for
    portrait).
    """

    length_seconds: Required[Annotated[int, PropertyInfo(alias="lengthSeconds")]]
    """Desired length of the video ad in seconds."""

    prompt: Required[str]
    """
    Textual description for the video ad generation, guiding the AI on content and
    narrative.
    """

    style: Required[Literal["Cinematic", "Documentary", "Animated", "Explainer", "Minimalist", "Vibrant"]]
    """Desired visual style for the video."""

    brand_colors: Annotated[Optional[SequenceNotStr[str]], PropertyInfo(alias="brandColors")]
    """
    Optional: Array of hex color codes to integrate into the video's branding and
    aesthetic.
    """

    keywords: Optional[SequenceNotStr[str]]
    """
    Optional: Specific keywords to emphasize in the visual or textual content
    generated by AI.
    """
