configured_endpoints: 105
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/citibank-demo-business-inc%2Fjames-burvel-ocallaghan-iii-7d0a891b51c471b8d5698cf0c15feea301dede6606eced18f940d4bcf27f2bfa.yml
openapi_spec_hash: 4a8b8ab6afe3453c584be039a2f6f7b2
config_hash: 98454d6b099ae2148555f64840f341b6
