# File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

from typing import List, Optional

from pydantic import Field as FieldInfo

from ...._models import BaseModel
from ...transactions.ai_insight import AIInsight

__all__ = ["ChatSendMessageResponse", "FunctionCall"]


class FunctionCall(BaseModel):
    id: Optional[str] = None
    """Unique ID for this tool call, used to link with `functionResponse`."""

    args: Optional[object] = None
    """Key-value pairs representing the arguments to pass to the tool function."""

    name: Optional[str] = None
    """The name of the tool function to call."""


class ChatSendMessageResponse(BaseModel):
    session_id: str = FieldInfo(alias="sessionId")
    """The active conversation session ID."""

    function_calls: Optional[List[FunctionCall]] = FieldInfo(alias="functionCalls", default=None)
    """A list of tool functions the AI wants the system to execute."""

    proactive_insights: Optional[List[AIInsight]] = FieldInfo(alias="proactiveInsights", default=None)
    """A list of proactive AI insights or recommendations generated by Quantum."""

    requires_user_action: Optional[bool] = FieldInfo(alias="requiresUserAction", default=None)
    """
    Indicates if the AI's response implies that the user needs to take a specific
    action (e.g., provide more input, confirm a tool call).
    """

    text: Optional[str] = None
    """The AI Advisor's textual response."""
